STYLE 코드 네이밍 규칙에 맞게 변경
Dusudgal/Etica pull request #5
Opened 2024-09-03 05:02 UTC by yujeong-claudia

STYLE 코드 네이밍 규칙에 맞게 변경
- 카멜케이스 수정 
- 회원가입 화면에서 핸드폰, 생년월일 숫자만 입력가능하게 변경
- 이용약관 필수/선택 분리

2024-09-04 12:39 UTC, dydwns requested changes

2024-09-04 12:39 UTC, dydwns commented on eticaPlanner/src/main/java/com/eticaplanner/eticaPlanner/user/UserController.java
> +    public String SignOut(HttpSession session){
```suggestion
    public String signOut(HttpSession session){
```
메서드는 소문자로 시작하는게 좋을거같아요

2024-09-04 12:39 UTC, dydwns commented on eticaPlanner/src/main/java/com/eticaplanner/eticaPlanner/user/UserController.java
> +        session.removeAttribute("user_name");
```suggestion
        session.invalidate();
```
동일한 역할을 할거 같아요

2024-09-04 12:39 UTC, dydwns commented on eticaPlanner/src/main/java/com/eticaplanner/eticaPlanner/user/UserRestController.java
> +            @RequestParam("user_gender") String user_gender){
Body에 넣지 않고 param으로 받으시는 이유가 있나요?

2024-09-04 12:39 UTC, dydwns commented on eticaPlanner/src/main/java/com/eticaplanner/eticaPlanner/user/UserRestController.java
> +        Integer userId = userService.addUser(user_id, hashed_password, user_name, user_phone, user_birth, user_gender);
user가 중복되는데 제거하는건 어떨까요? 기존 코드도 나쁘지 않아보여요

2024-09-04 12:39 UTC, dydwns commented on eticaPlanner/src/main/java/com/eticaplanner/eticaPlanner/user/UserRestController.java
> +            @RequestParam("user_password") String user_password,
`@RequestParam` 쓰면 query String 으로 비밀번호가 노출될것 같아요
`@RequestBody`로 넘기는건 어떤가요?

2024-09-06 01:10 UTC, Dusudgal commented
메서드 네이밍 규칙만 지켜주시면 좋을것같습니다~

2024-09-06 01:10 UTC, merged